Revert "Bump h2 from 1.4.199 to 1.4.200"
This reverts commit bf493eb1b3ffc6c65c37d53596f869b9e7d56d9e.

The original commit seems to result in this test error:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Validate failed:
        Detected failed migration to version 35 (add unknown auth method to request audit record)