fix: internal constant that's no longer visible
* Rather than try to use a default that wasn't intended to be imported, hardcode the value in the code.

* Fixes these build errors:

/workspace/credhub/components/encryption/src/main/java/org/cloudfoundry/credhub/services/KMSEncryptionProvider.java:36: error: package io.grpc.internal does not exist
import static io.grpc.internal.GrpcUtil.DEFAULT_KEEPALIVE_TIMEOUT_NANOS;

/workspace/credhub/components/encryption/src/main/java/org/cloudfoundry/credhub/services/KMSEncryptionProvider.java:36: error: static import only from classes and interfaces
import static io.grpc.internal.GrpcUtil.DEFAULT_KEEPALIVE_TIMEOUT_NANOS;

/workspace/credhub/components/encryption/src/main/java/org/cloudfoundry/credhub/services/KMSEncryptionProvider.java:64: error: cannot find symbol
        .keepAliveTime(DEFAULT_KEEPALIVE_TIMEOUT_NANOS, TimeUnit.NANOSECONDS)
                       ^
  symbol:   variable DEFAULT_KEEPALIVE_TIMEOUT_NANOS
  location: class KMSEncryptionProvider

e: file:///workspace/credhub/backends/remote/src/main/kotlin/org/cloudfoundry/credhub/remote/RemoteBackendClient.kt:4:16 Unresolved reference: internal

e: file:///workspace/credhub/backends/remote/src/main/kotlin/org/cloudfoundry/credhub/remote/RemoteBackendClient.kt:81:32 Unresolved reference: DEFAULT_KEEPALIVE_TIMEOUT_NANOS