Revert "Build(deps): bump springBootVersion from 2.6.8 to 2.7.2"
This reverts commit 34b2af0e5fa031341ea94534d3160b52773392fd.

due to test failure:
```
org.cloudfoundry.credhub.services.CertificateDataServiceTest > findAllValidMetadata returns certificate with null expiryDate when none exists FAILED
    java.lang.IllegalArgumentException: Expected byte[] or UUID type. Received class java.lang.String
        at org.cloudfoundry.credhub.services.CertificateDataService.toUUID(CertificateDataService.kt:121)
        at org.cloudfoundry.credhub.services.CertificateDataService.findAllValidMetadata(CertificateDataService.kt:79)
        at org.cloudfoundry.credhub.services.CertificateDataServiceTest.findAllValidMetadata returns certificate with null expiryDate when none exists(CertificateDataServiceTest.kt:86)
```