fix: various unit test failures due to InvalidDataAccessResourceUsageException
- after bumping to spring boot 3 (which also bumps hibernate to 6.6.x)
- error:
```
org.springframework.dao.InvalidDataAccessResourceUsageException: Unable to find column position by name: password_parameters_uuid [No such column: 'password_parameters_uuid'.
```
in `DefaultCredentialVersionDataServiceTest` and `CertificateMigrationTest`. This is confusing because for the data (certificate credentials) we are trying to access in this use case, we don't actually need `password_parameters_uuid` (only needed for password credentials).
- analysis:
  - in reality, column `password_parameters_uuid` is in table `password_credential` which becomes, along with data from some other tables, the specific entity `CredentialVersionData<PasswordCredentialVersionData>` (see code: https://github.com/cloudfoundry/credhub/blob/5f22e43bedd3f73623367c3e863a16294e9cff49/components/credentials/src/main/kotlin/org/cloudfoundry/credhub/entity/PasswordCredentialVersionData.kt#L23).
  - the query functions in `CredentialVersionRepository` (changed in this commit) used to return `CredentialVersionData<*>`, which is not specific enough, potentially confusing Hibernate into confusing it with / lumping it with `CredentialVersionData<PasswordCredentialVersionData>`.
  - In reality, the specific type required here is `CertificateCredentialVersionData` (which is a `CredentialVersionData<*>` but is more specific) which does not need `password_parameters_uuid`.
  - hence, change the return type into the more specific type, so Hibernate can be sure that we don't need `password_parameters_uuid` column.

[https://vmw-jira.broadcom.net/browse/TNZ-41345]