fix test: org.hibernate.TransientObjectException
- the error is:
```
org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientObjectException: persistent instance references an unsaved transient instance of 'org.cloudfoundry.credhub.entity.Credential' (save the transient instance before flushing)
```
which happens at all tests where `@Transactional` is in effect and the
test: 1) deletes some data created in the same method or in
beforeEach/beforeAll lifecycle methods 2) and then perform any
operations interacting with DB.

- this error shows up after upgrading to hibernate 6.6.x+, possibly
  related to:
https://discourse.hibernate.org/t/instance-save-transient-before/10293
https://hibernate.atlassian.net/browse/HHH-18936
  - the general idea is that related entities are not properly cleaned
    up, leading to orphaned data in cache / DB?

- it is still not clear to me the exact reasons why `@Transactional`
  (which mainly ensures the test method is executed within a transaction and
  automatically roll back after the test completes) will cause this
  error, or why this error did not show up when using older version of
  hibernate. But it seems plausible that it might create unintended side
  effects.

- this exclusion of `@Transactional` has precedents in our code: https://github.com/cloudfoundry/credhub/commit/34fd70c43427dd80979a67c6eda9dd37155fcd0b
  - reference: https://docs.spring.io/spring-framework/reference/data-access/transaction/declarative/applying-more-than-just-tx-advice.html

- this exclusion of `@Transactional` for this test also results in the
  lack of `@Transactional` for the `@Before` step before this test, which
  means the data inserted in `@Before` is not rolled back upon test
  completion (for this test method only), which will lead to test
  pollution. So to make sure all inserted data is rolled back, also
  delete the other test credential added in `@Before` (which fits the
  theme of this test method anyway).

[https://vmw-jira.broadcom.net/browse/TNZ-42725]