fix: postgres script error
- Fixed the drop operation order for the following error:
```
ERROR: cannot drop function del_credential_version_encrypted_value() because other objects depend on it
  Detail: trigger tr_credential_version_post_del on table credential_version depends on function del_credential_version_encrypted_value()
```