revert: Commits merged from 182121168-del-encrypted_values branch
- f27576b8a30fc0978be2865e4f779ea58cae7e7e..
- As they caused two kinds of test failures as follows.
- A unit test case failure for mysql & postgres15:
```
org.cloudfoundry.credhub.integration.CertificateVersionDeleteTest > deleteCertificateVersion_whenThereAreOtherVersionsOfTheCertificate_deletesTheSpecifiedVersion FAILED
    org.json.JSONException: Value {"error":"An application error occurred. Please contact your CredHub administrator."} of type org.json.JSONObject cannot be converted to JSONArray
        at app//org.json.JSON.typeMismatch(JSON.java:111)
        at app//org.json.JSONArray.<init>(JSONArray.java:96)
        at app//org.json.JSONArray.<init>(JSONArray.java:108)
        at app//org.cloudfoundry.credhub.integration.CertificateVersionDeleteTest.deleteCertificateVersion_whenThereAreOtherVersionsOfTheCertificate_deletesTheSpecifiedVersion(CertificateVersionDeleteTest.java:103)
```
- Failure with postgres13, which indicates that the trigger code is not compatible with postgres13:
```
org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V57_2__delete_related_encrypted_value_when_credential_is_deleted.sql failed
SQL State  : 42601
Error Code : 0
Message    : ERROR: syntax error at or near "TRIGGER"
Position: 19

```
[#182121168]