fix: build error due to compatibility between flyway 12 and spring-boot 3.5.10 - As follows: ``` java.lang.NoSuchMethodError: 'org.flywaydb.core.api.configuration.FluentConfiguration org.flywaydb.core.api.configuration.FluentConfiguration.cleanOnValidationError(boolean)' 	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.lambda$configureProperties$26(FlywayAutoConfiguration.java:267) ``` - Bumped spring-boot to 3.5.11 as it was fixed by https://github.com/spring-projects/spring-boot/commit/69eae29 in that version.